[prune]
  go-tests = true
  non-go = true
  unused-packages = true

[[constraint]]
  name = "github.com/fatih/color"
  version = "^1.5.0"

[[constraint]]
  name = "github.com/hashicorp/consul"
  version = "^0.9.2"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "^0.8.0"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "^1.1.4"

[[constraint]]
  name = "gopkg.in/DATA-DOG/go-sqlmock.v1"
  version = "^1.2.0"

# PMM-2569: Version 1.4.0 introduces support for new auth methods in MySQL 8.
[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "^1.4.0"
